### ISSUE TITLE
P. 200  [어노테이션으로 변경 후 오류발생]

### ISSUE THREAD

**Issue by lua928908** [jojoldu/freelec-springboot2-webservice#133]
**오류 내용**
194 페이지 까지 실습이후 정상적으로 동작하는 것을 확인했습니다!
그런데 195 ~ 200 페이지까지 '어노테이션으로 개선하기' 부분을 진행한 이후에
오류가 발생하고 있습니다. 제가 대략 이해 하기로는 customOAuth2UserService 에서 주입받는
빈이 동일해서 문제가 생기는듯 싶은데.. 스프링부트의 기본을 잘 모르다보니 195페이지부터 다시 확인해보아도 혼자 해결이안되 이렇게 또 질문드립니다 ㅜ

시간이 괜찮으실 때 고견 나눠주실수 있으시다면 너무 감사하겠습니다.
 

**Github URL:   https://github.com/lua928908/springboot_board**

### 오류 로그

```
2020-01-05 15:03:09.577  INFO 10656 --- [           main] com.where.springboot.Application         : Starting Application on DESKTOP-C32TCMU with PID 10656 (C:\Users\lua92\Desktop\Github\SpringBoot_Board\build\classes\java\main started by lua92 in C:\Users\lua92\Desktop\Github\SpringBoot_Board)
2020-01-05 15:03:09.580  INFO 10656 --- [           main] com.where.springboot.Application         : The following profiles are active: oauth
2020-01-05 15:03:09.936  WARN 10656 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanDefinitionStoreException: Failed to parse configuration class [com.where.springboot.Application]; nested exception is org.springframework.context.annotation.ConflictingBeanDefinitionException: Annotation-specified bean name 'customOAuth2UserService' for bean class [com.where.springboot.configure.auth.CustomOAuth2UserService] conflicts with existing, non-compatible bean definition of same name and class [com.where.springboot.config.auth.CustomOAuth2UserService]
2020-01-05 15:03:09.982 ERROR 10656 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanDefinitionStoreException: Failed to parse configuration class [com.where.springboot.Application]; nested exception is org.springframework.context.annotation.ConflictingBeanDefinitionException: Annotation-specified bean name 'customOAuth2UserService' for bean class [com.where.springboot.configure.auth.CustomOAuth2UserService] conflicts with existing, non-compatible bean definition of same name and class [com.where.springboot.config.auth.CustomOAuth2UserService]
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:181) ~[spring-context-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:315) ~[spring-context-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:232) ~[spring-context-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:275) ~[spring-context-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:95) ~[spring-context-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:705) ~[spring-context-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:531) ~[spring-context-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) ~[spring-boot-2.1.9.RELEASE.jar:2.1.9.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:744) [spring-boot-2.1.9.RELEASE.jar:2.1.9.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:391) [spring-boot-2.1.9.RELEASE.jar:2.1.9.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312) [spring-boot-2.1.9.RELEASE.jar:2.1.9.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) [spring-boot-2.1.9.RELEASE.jar:2.1.9.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1204) [spring-boot-2.1.9.RELEASE.jar:2.1.9.RELEASE]
	at com.where.springboot.Application.main(Application.java:19) [main/:na]
Caused by: org.springframework.context.annotation.ConflictingBeanDefinitionException: Annotation-specified bean name 'customOAuth2UserService' for bean class [com.where.springboot.configure.auth.CustomOAuth2UserService] conflicts with existing, non-compatible bean definition of same name and class [com.where.springboot.config.auth.CustomOAuth2UserService]
	at org.springframework.context.annotation.ClassPathBeanDefinitionScanner.checkCandidate(ClassPathBeanDefinitionScanner.java:348) ~[spring-context-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.context.annotation.ClassPathBeanDefinitionScanner.doScan(ClassPathBeanDefinitionScanner.java:286) ~[spring-context-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.context.annotation.ComponentScanAnnotationParser.parse(ComponentScanAnnotationParser.java:132) ~[spring-context-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:287) ~[spring-context-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:242) ~[spring-context-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:199) ~[spring-context-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:167) ~[spring-context-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	... 13 common frames omitted


Process finished with exit code 1

```

**Comment by jojoldu** [comment]
@lua928908 님 안녕하세요!
방금 해당 프로젝트를 받아서 실행해보았는데요.
정상적으로 실행이 되는데 
혹시 어떨떄 위와 같이 에러가 발생하시나요?
테스트 코드에서 발생하시는걸까요?

**Comment by lua928908** [comment]
헉... 아뇨 Application 클래스에서 main 클래스를 run, 실행했을때 발생하고있는 오류입니다..ㅜ

**Comment by lua928908** [comment]
아! 지금 잘된다고 하셔서 깃에서 다시 다운받아 실행해봤는데 저도 실행이 되고있습니다...
죄송합니다 ㅜㅜ 무슨이유인지 모르겠지만 change된 파일이 없었는데.. 다시다운받아서 실행을 하니
localhost:8080에서도 동작하는게 확인되고있네요

**Comment by jojoldu** [comment]
@lua928908 앗 넵넵 ㅎㅎ 뭔가 컴파일된 .class 파일에 문제가 있었나봅니다 :)
잘되셔서 다행이에요!

**Comment by lua928908** [comment]
시간쓰셨을텐데 죄송하고 감사합니다.
