### ISSUE TITLE
[오류] p.358 travis 오류 및 deploy 오류입니다.

### ISSUE THREAD

**Issue by hoonpig** [jojoldu/freelec-springboot2-webservice#245]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

### 어떤 오류인가요?

오류설명: travis ci 빌드시 하기의 오류가 발생합니다. 이게 발생할때도 있고, 발생해서 deploy.sh 파일등에 echo부분 . 을찍어서 빌드하면 정상적으로 될때도있고 합니다..

아무리찾아봐도 이게 왜발생하는지 어려움에..자문을구합니다..ㅠㅠ

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.  
**Github 주소를 작성해주지 않으시면 답변해드릴수가 없어요!**

* Github URL: https://github.com/hoonpig/hoonpig_springboot

### 오류 로그

org.springframework.transaction.CannotCreateTransactionException: Could not open JPA EntityManager for transaction; nested exception is java.lang.IllegalStateException: EntityManagerFactory is closed
	at org.springframework.orm.jpa.JpaTransactionManager.doBegin(JpaTransactionManager.java:446) ~[spring-orm-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:378) ~[spring-tx-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:137) ~[spring-tx-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.session.jdbc.JdbcOperationsSessionRepository.cleanUpExpiredSessions(JdbcOperationsSessionRepository.java:619) ~[spring-session-jdbc-2.1.8.RELEASE.jar:2.1.8.RELEASE]
	at org.springframework.session.jdbc.config.annotation.web.http.JdbcHttpSessionConfiguration.lambda$configureTasks$0(JdbcHttpSessionConfiguration.java:213) ~[spring-session-jdbc-2.1.8.RELEASE.jar:2.1.8.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_222]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_222]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_222]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_222]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_222]
Caused by: java.lang.IllegalStateException: EntityManagerFactory is closed
	at org.hibernate.internal.SessionFactoryImpl.validateNotClosed(SessionFactoryImpl.java:531) ~[hibernate-core-5.3.10.Final.jar:5.3.10.Final]
	at org.hibernate.internal.SessionFactoryImpl.createEntityManager(SessionFactoryImpl.java:613) ~[hibernate-core-5.3.10.Final.jar:5.3.10.Final]
	at org.hibernate.internal.SessionFactoryImpl.createEntityManager(SessionFactoryImpl.java:154) ~[hibernate-core-5.3.10.Final.jar:5.3.10.Final]
	at org.springframework.orm.jpa.JpaTransactionManager.createEntityManagerForTransaction(JpaTransactionManager.java:464) ~[spring-orm-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.orm.jpa.JpaTransactionManager.doBegin(JpaTransactionManager.java:390) ~[spring-orm-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	... 13 common frames omitted

**Comment by camel-master** [comment]
만약deploy.sh의 내용중 nohup 관련된 부분에 application-real.properties로 되어있다면 
application-real-db.properties로 변경해보시겠어요?

**Comment by hoonpig** [comment]
흠...둘다 등록이 되어있는 상태네요..ㅠㅠ
-Dspring.config.location=
   classpath:/application.properties,classpath:/application-real.properties,
   /home/ec2-user/app/application-oauth.properties,
  /home/ec2-user/app/application-real-db.properties \

**Comment by hoonpig** [comment]
흠...혹시몰라 자세히보니 다른점이있어서 적용하고났더니 그래도 동일한에러가 났다가,,,안났다가.,...그러네요...

**Comment by camel-master** [comment]
(수정전)
-Dspring.config.location=
classpath:/application.properties,classpath:/application-real.properties,
/home/ec2-user/app/application-oauth.properties,
/home/ec2-user/app/application-real-db.properties \

(수정후)
-Dspring.config.location=
classpath:/application.properties,classpath:/application-real**### -db**.properties,
/home/ec2-user/app/application-oauth.properties,
/home/ec2-user/app/application-real-db.properties \

**Comment by camel-master** [comment]
혹시 /home/ec2-user/app 디렉토리에 application-real.properties 가 있는지요?

**Comment by camel-master** [comment]
-Dspring.config.location=
classpath:/application.properties,classpath:/application-real.properties,
/home/ec2-user/app/application-oauth.properties,
/home/ec2-user/app/application-real-db.properties \

에서 다음과 같이 classpath://application-real.properties를 제거해보시겠어요?

-Dspring.config.location=classpath:/application.properties,/home/ec2-user/app/application-oauth.properties,/home/ec2-user/app/application-real-db.properties \

**Comment by hoonpig** [comment]
@camel-master  답변감사합니다 :)
확인해보았는데 오타는 없네요 ㅎㅎㅎ 조금더 찾아봐야겠어요

**Comment by RimChoi** [comment]
@hoonpig 몇 일째 같은 에러로 찾고있는데요. 혹시 해결하셨는지요 ㅠㅠ

**Comment by feelsocold** [comment]
혹시 해결하셨나요? Travis에서 다시 빌드하면 passed 뜨기도하고 같은 에러로그 뜨면서 안되기도 하네요ㅠㅠ

**Comment by zhtmr** [comment]
저도 jpa 오류 뜨면서 travis 에서 빌드가 안되네요

**Comment by zhtmr** [comment]
![image](https://user-images.githubusercontent.com/48509269/79304621-bd556400-7f2c-11ea-8a96-0ae45d649bc7.png)
저는 저번에 livereload 관련 설정을 application.properties에 해놨었는데 이거 주석처리 하니까 제대로 빌드 되네요..

**Comment by zhtmr** [comment]
저도 해당 오류로 한달내내 삽질중이네요......... 아무리 찾아도 모르겠습니다

**Comment by jon890** [comment]
혹시 해결하신분 없나요 ㅠㅠ... 오류가 떳다 안떳다해서 이게 빌드 자동화같지가 않은느낌이네요...

**Comment by ssw207** [comment]
유사한 에러 해결해서 글 남깁니다

에러로그

org.springframework.transaction.CannotCreateTransactionException: Could not open JPA EntityManager for transaction; nested exception is java.lang.IllegalStateException: EntityManagerFactory is closed
	at org.springframework.orm.jpa.JpaTransactionManager.doBegin(JpaTransactionManager.java:446) ~[spring-orm-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:378) ~[spring-tx-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:137) ~[spring-tx-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.session.jdbc.JdbcOperationsSessionRepository.cleanUpExpiredSessions(JdbcOperationsSessionRepository.java:619) ~[spring-session-jdbc-2.1.8.RELEASE.jar:2.1.8.RELEASE]
	at 


저는 EC2에서 직접 빌드스크립트 실행시 정상빌드되나 인텔리제이에서 빌드시 + travisCI에서 빌드시 위와 같은 에러가 발생했습니다.

build.gradle에 dependency 작성시

testCompile group: 'org.springframework.security', name: 'spring-security-test', version: '5.3.3.RELEASE'

위처럼 작성한 부분을 아래처럼 바꾸니 정상 빌드 되네요.

testCompile('org.springframework.boot:spring-boot-starter-test')

정확한 원인은 알수 없으나 그래들 버전간 문법호환 문제가 아닌가 싶습니다.

**Comment by fortunerain** [comment]
혹시 해결 되셨나요?

**Comment by geniusdew** [comment]
저도....ㅠㅠ 해결하신분 없나요...

**Comment by parksil0** [comment]
혹시나 해서 제가 해결한 방법을 공유합니다!
src/main/resources/application.properties 의 내용 중,

`spring.profiles.include=oauth`
에서

`spring.profiles.include=real-oauth`
로 수정한 후 푸쉬 후 해결되었습니다.

**Comment by ybell1028** [comment]
저도 https://travis-ci.org/에선 통과하는데 https://travis-ci.com/에서 질문 같은 오류가 계속 뜨네요...

**Comment by breadmk** [comment]
2가지를 변경했는데 무엇때문에 해결됐는지 모르겠습니다만

그 중의 하나는

implementation 'org.springframework.boot:spring-boot-starter-test' 
이 소스를
testImplementation 'org.springframework.boot:spring-boot-starter-test' 
변경하였습니다.

위의 @ssw207 님의 내용을 참고해서 변경하였으며,

2번째는 

인프런의 김영한 님의 답변을 참고했습니다.
https://www.inflearn.com/questions/60157 
같은 에러현상입니다.

org.springframework.transaction.CannotCreateTransactionException: Could not open JPA EntityManager for transaction; nested exception is java.lang.IllegalStateException: EntityManagerFactory is closed

이 에러코드를 localhost에서도 나오게 했는데 그건 h2-console를 닫아놓으면 나왔습니다.

그래서 빌드전에 h2-console을 열어놓고 빌드하니 정상적으로

![image](https://user-images.githubusercontent.com/74883958/142350996-3d78c115-55d3-42c3-8850-c96f84bafda4.png)

빌드되었습니다.

늦었지만 많은 도움이 되었으면 합니다.
