### ISSUE TITLE
[오류] p.318  네이버 로그인 한글 깨짐으로 인한 SQLException

### ISSUE THREAD

**Issue by darren9352** [jojoldu/freelec-springboot2-webservice#317]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

## 가장 자주 나온 제보

* [P.105 @PutMapping("/api/v1/posts")](https://github.com/jojoldu/freelec-springboot2-webservice/issues/6)
* [P.111 Posts.update](https://github.com/jojoldu/freelec-springboot2-webservice/issues/15)

### 어떤 오류인가요?

오류설명: RDS에서 character_set 이랑 collation을 모두 utf8mb4와 utf8mb4_general_ci로 바꿨음에도 불구하고 네이버 로그인 할때 한글이 깨져서 SQLException이 발생 합니다.

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.  
**Github 주소를 작성해주지 않으시면 답변해드릴수가 없어요!**

* Github URL: https://github.com/darren9352/springboot-aws
* 전체 로그: https://github.com/darren9352/springboot-aws/blob/master/nohup.out

### 오류 로그

```
Caused by: java.sql.SQLException: Incorrect string value: '\xEC\xB5\x9C\xED\x98\x84...' for column `springboot_aws`.`user`.`name` at row 1
Query is: insert into user (created_date, modified_date, email, name, picture, role) values (?, ?, ?, ?, ?, ?), parameters ['2020-03-13 02:59:07.699','2020-03-13 02:59:07.699','darren93@naver.com','최현빈',<null>,'GUEST']
java thread: http-nio-8080-exec-6
	at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:163) ~[mariadb-java-client-2.3.0.jar!/:na]
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:280) ~[mariadb-java-client-2.3.0.jar!/:na]
	at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:223) ~[mariadb-java-client-2.3.0.jar!/:na]
	... 121 common frames omitted
```

어떤 오류인지 캡쳐해주세요.

**Comment by changjinpark** [comment]
저랑 동일한 이슈를 겪으셨네요. 저는 user 테이블의 캐릭터셋을 utf8로 변경해서 해결했습니다. 

ALTER TABLE [테이블이름] CONVERT TO character SET utf8;
