### ISSUE TITLE
[오류] p.76

### ISSUE THREAD

**Issue by eunsoo8606** [jojoldu/freelec-springboot2-webservice#442]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

## 가장 자주 나온 제보

* [P.105 @PutMapping("/api/v1/posts")](https://github.com/jojoldu/freelec-springboot2-webservice/issues/6)
* [P.111 Posts.update](https://github.com/jojoldu/freelec-springboot2-webservice/issues/15)

### 어떤 오류인가요?
Status expected:<200> but was:<401>
Expected :200
Actual   :401
`<Click to see difference>

java.lang.AssertionError: Status expected:<200> but was:<401>
	at org.springframework.test.util.AssertionErrors.fail(AssertionErrors.java:59)
	at org.springframework.test.util.AssertionErrors.assertEquals(AssertionErrors.java:98)
	at org.springframework.test.web.servlet.result.StatusResultMatchers.lambda$matcher$9(StatusResultMatchers.java:619)
	at org.springframework.test.web.servlet.MockMvc$1.andExpect(MockMvc.java:196)
	at com.jojodu.book.springboot.web.dto.HelloResponseDtoTest.helloDto가_리턴된다(HelloResponseDtoTest.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestExecutionCallbacks.evaluate(RunBeforeTestExecutionCallbacks.java:74)
	at org.springframework.test.context.junit4.statements.RunAfterTestExecutionCallbacks.evaluate(RunAfterTestExecutionCallbacks.java:84)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)`

오류설명:
HelloDto가 리턴된다() 메소드를 책과 맞게 처음에는 직접 만들어 실행했더니
.andExpect(status().isOk())<- 이라인에서 계속 에러가 납니다.
### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.  
**Github 주소를 작성해주지 않으시면 답변해드릴수가 없어요!**

* Github URL: 
https://github.com/eunsoo8606/freelec-springboot2

### 오류 로그

어떤 오류인지 캡쳐해주세요
![캡처](https://user-images.githubusercontent.com/67855235/86788621-56fe5e80-c0a1-11ea-86a5-ee16cd284b38.PNG)
.

**Comment by nueey** [comment]
혹시 해결 하셨나요??

**Comment by jipang9** [comment]
build.gradle - dependency 부분에  시큐리티를 빌드해서 사용하신게 아닌가 싶네요, 저도 똑같은 오류가 발생하였고, 에러에 대해 검색했는데, 결국 401 에러는 클라이언트 인증 관련 에러인데  저도 그냥 나중에 어차피 시큐리티 사용할 것이니까 미리 빌드해놨던 것이 문제가 됐네요. 시큐리티를 날리고 다시 돌리니까 잘 됩니다. 아직 해결하셨을지 모르겠지만 한 번 확인해보세용...
