### ISSUE TITLE
[오류] p.133

### ISSUE THREAD

**Issue by euijeonghwang** [jojoldu/freelec-springboot2-webservice#649]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

## 가장 자주 나온 제보

* [P.105 @PutMapping("/api/v1/posts")](https://github.com/jojoldu/freelec-springboot2-webservice/issues/6)
* [P.111 Posts.update](https://github.com/jojoldu/freelec-springboot2-webservice/issues/15)

### 어떤 오류인가요?

오류설명: mustache 플러그인 설치하고, build.,gradle에 추가했는데 테스트 결과 수행시 404 에러가 뜹니다. 에러가 자꾸 나서 그대로 복붙했는데도 테스트 통과를 못하네요

### 프로젝트 주소

Github에 오류가 난 프로젝트를 올려주세요.  
**Github 주소를 작성해주지 않으시면 답변해드릴수가 없어요!**

* Github URL: https://github.com/euijeonghwang/springboot-aws-webservice

### 오류 로그

java.lang.AssertionError: 
Expecting:
 <"{"timestamp":"2021-05-23T06:08:06.114+0000","status":404,"error":"Not Found","message":"No message available","path":"/"}">
to contain:
 <"스프링 부트로 시작하는 웹 서비스"> 

	at com.jojoldu.book.springboot.web.IndexControllerTest.메인페이지_로딩(IndexControllerTest.java:25)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestExecutionCallbacks.evaluate(RunBeforeTestExecutionCallbacks.java:74)
	at org.springframework.test.context.junit4.statements.RunAfterTestExecutionCallbacks.evaluate(RunAfterTestExecutionCallbacks.java:84)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:251)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:221)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)

**Comment by xxx-sj** [comment]
이와같은 오류로 검색해서 들어오신 분들을 위해 남깁니다. 
해당 오류같은 경우 resoures 하위에 폴더명이 잘못되었다거나 [ templates 가 아닌 template ] 혹은 index.mustache 가 아닌 
index.mustache.html 파일인 경우가 있습니다. 오타가 없는지 한번 더 확인 하시면 될 것 같습니다.

src/main/resources/templates 가 맞는지 확인해보기
templates 폴더 안에 index.mustache 가 맞는지 확인하기

**Comment by NamkungJ** [comment]
build.gradle을 확인해보세요.
저도 동일한 오류 compile('org.springframework.boot:spring-boot-starter-mustache') 를 지우고 다시 해보니 정상 실행 되네요.

**Comment by zooxop** [comment]
저도 동일한 오류때문에 찾다가 여기까지 왔고, 해결한 뒤 글 남깁니다.

build.gradle 의 dependency 영역에 
  testCompile('org.springframework.boot:spring-boot-starter-mustache');
을 추가해줬더니 문제가 해결되었습니다.

저의 경우는,
  complie('org.springframework.boot:spring-boot-starter-mustache');
만 추가해놓았더니, 톰캣을 실행해서 직접 localhost:8080/ 으로 들어가봤을때는 잘 됐는데, 테스트에서만 오류가 발생하는 상황이었습니다.
