### ISSUE TITLE
[오류] p.110

### ISSUE THREAD

**Issue by g16rim** [jojoldu/freelec-springboot2-webservice#863]
기존에 올라온 질문이 아닌지 먼저 검색해주세요!

## 가장 자주 나온 제보

* [P.105 @PutMapping("/api/v1/posts")](https://github.com/jojoldu/freelec-springboot2-webservice/issues/6)
* [P.111 Posts.update](https://github.com/jojoldu/freelec-springboot2-webservice/issues/15)

### 어떤 오류인가요?

오류설명: 그전 실습까지는 잘 되다가 PostsApiController에서 에러가 나네요.
github 코드로도 해보고, 책에 있는 코드로도 해보는데도 잘 안 되네요...

### 프로젝트 주소

* Github URL: 

### 오류 로그
![image](https://user-images.githubusercontent.com/79007826/211836935-d46d04b8-c454-4722-9b31-1726d743c949.png)

**Comment by g16rim** [comment]
org.springframework.web.client.ResourceAccessException: I/O error on POST request for "http://localhost:8080/api/v1/posts": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect

	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:744)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:670)
	at org.springframework.web.client.RestTemplate.postForEntity(RestTemplate.java:445)
	at org.springframework.boot.test.web.client.TestRestTemplate.postForEntity(TestRestTemplate.java:489)
